import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import HomeHero from "components/HomeHero";
import FeatureHome from "../components/FeaturesHome";
import HomeCta from "../components/HomeCta";
import Testimonial from "../components/Testimonial";
import Footer from "../components/Footer";
import OtherInfo from "../components/OtherInfoHome";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Abogada Diana Olivo Moreira</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeHero />
      <FeatureHome />
      <HomeCta />
      <Testimonial />
      <OtherInfo />
      <Footer />
    </>
  );
}
